
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-worker
  labels:
    app: benchmark-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: benchmark-worker
  template:
    metadata:
      labels:
        app: benchmark-worker
    spec:
      containers:
        - name: nginx
          image: docker.io/linulun/benchmark-worker:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: benchmark-worker-svc
spec:
  type: LoadBalancer
  selector:
    app: benchmark-worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
