name: Java CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
                  cache: "maven"
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: "6.0"
            - name: Build and test PerformanceBot
              run: cd performancebot && mvn clean test && cd ..
            - name: Build and test BenchmarkWorker
              run: cd benchmarkworker && mvn clean test && cd ..
